name: sampleflutter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  firebase_analytics: ^10.10.5
  cloud_firestore: ^4.17.3
  provider: ^5.0.0
  flutter_slidable: ^3.1.0
  firebase_storage: ^11.7.5
  image_picker: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - images/janken.jpg
    - images/title.png
    - images/cleartitle.png
