// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaQQ_Bznk8J906Q9vO2QhzpJ6bNdFpvh0',
    appId: '1:935256137371:web:562be2d9db58275145b03e',
    messagingSenderId: '935256137371',
    projectId: 'chatwithfirebaseapp-8824c',
    authDomain: 'chatwithfirebaseapp-8824c.firebaseapp.com',
    storageBucket: 'chatwithfirebaseapp-8824c.appspot.com',
    measurementId: 'G-4KBVM3CQ96',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF6m3lyb1NV-HwkiNIvKIbmaN63GffR9g',
    appId: '1:281742276791:android:3306d20087a653a7a7f532',
    messagingSenderId: '281742276791',
    projectId: 'sampleflutter-29f1d',
    storageBucket: 'sampleflutter-29f1d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7_39bqbzGj6gAn8FA38mQNwbaNWUhvyE',
    appId: '1:281742276791:ios:84ab433961ea914ca7f532',
    messagingSenderId: '281742276791',
    projectId: 'sampleflutter-29f1d',
    storageBucket: 'sampleflutter-29f1d.appspot.com',
    iosBundleId: 'com.example.sampleflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDoI0vOaV_1HCggri19qzAOQJiGNR6Dgw',
    appId: '1:935256137371:ios:59f3df6e40c2c00645b03e',
    messagingSenderId: '935256137371',
    projectId: 'chatwithfirebaseapp-8824c',
    storageBucket: 'chatwithfirebaseapp-8824c.appspot.com',
    iosBundleId: 'com.example.sampleflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaQQ_Bznk8J906Q9vO2QhzpJ6bNdFpvh0',
    appId: '1:935256137371:web:a0931751d5b8c05445b03e',
    messagingSenderId: '935256137371',
    projectId: 'chatwithfirebaseapp-8824c',
    authDomain: 'chatwithfirebaseapp-8824c.firebaseapp.com',
    storageBucket: 'chatwithfirebaseapp-8824c.appspot.com',
    measurementId: 'G-EFGKP5TQPM',
  );
}